### ISSUE TITLE
Web Code Notes

### ISSUE THREAD

**Issue by abcwyc** [abcwyc/Notes#2]
## CSS
* opacity 不透明

* css float obscure 示例
```css
/*-----------float obscure----------*/
        .sample{
            float: left;
        }
        .clearfix:after{
            content:'.';
            display: block;
            clear: both;
            height: 0;
            overflow: hidden;
            visibility: hidden;
        }
/*-----------float obscure----------*/
```

## JavaScript
* 要查看一个变量的内容，在`Console`中输入`console.log(a);`，回车后显示的值就是变量的内容。
* `'use strict';`  strict模式
* JavaScript为字符串提供了一些常用方法，注意，调用这些方法本身不会改变原有字符串的内容，而是返回一个新字符串：
1. `toUpperCase()`把一个字符串全部变为大写;
2. `toLowerCase()`把一个字符串全部变为小写;
3. `indexOf()`会搜索指定字符串出现的位置;
4. `substring()`返回指定索引区间的子串;
