### ISSUE TITLE
双飞翼布局

### ISSUE THREAD

**Issue by abcwyc** [abcwyc/Notes#6]
### 双飞翼布局
> 双飞翼布局主要解决两个问题：  
> - 三列布局，中间宽度自适应，两边定宽；   
> - 中间栏主题内容可以浏览器中优先渲染。

- 示例如下：

```html
<div class="container">
		<div class="main">
			<div class="content"></div>
		</div>
		<div class="sub"></div>
		<div class="extra"></div>
	</div>
```

```css
		.container{
			width: 100%;
			overflow: hidden;
		}
		.main,.sub,.extra{
			float: left;
			padding-bottom: 9999px;
			margin-bottom: -9999px;
		}
		.main{
			width: 100%;
		}
		.main .content{
			min-height: 300px;
			margin: 0 210px 0 310px;
			background: #ccc;
		}
		.sub{
			width: 300px;
			margin-left: -100%;
			background: orange;
		}
		.extra{
			width:200px;
			margin-left: -200px;
			background: pink;
		}
 ```
![qq 20150929213559](https://cloud.githubusercontent.com/assets/8427883/10165539/71258c7e-66f2-11e5-90bb-03f7b4de2e6e.jpg)
